// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWxV5JK9ISAj3gKe0Nor7antp56jmJw9U',
    appId: '1:819197900013:web:77576fe50f0691c914c8e4',
    messagingSenderId: '819197900013',
    projectId: 'firetest-cdce4',
    authDomain: 'firetest-cdce4.firebaseapp.com',
    storageBucket: 'firetest-cdce4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9pCL5hw5T-KnjkarhQ0E-N7At7Vtyr9o',
    appId: '1:819197900013:android:1bb82d83c96ab6ab14c8e4',
    messagingSenderId: '819197900013',
    projectId: 'firetest-cdce4',
    storageBucket: 'firetest-cdce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_5hncsg0XpdROY7gLNmqcoZT-THXsfpE',
    appId: '1:819197900013:ios:23b69cc18013b59214c8e4',
    messagingSenderId: '819197900013',
    projectId: 'firetest-cdce4',
    storageBucket: 'firetest-cdce4.appspot.com',
    iosClientId: '819197900013-81vv1eoefp4j0mqvoquathjurro3st6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_5hncsg0XpdROY7gLNmqcoZT-THXsfpE',
    appId: '1:819197900013:ios:23b69cc18013b59214c8e4',
    messagingSenderId: '819197900013',
    projectId: 'firetest-cdce4',
    storageBucket: 'firetest-cdce4.appspot.com',
    iosClientId: '819197900013-81vv1eoefp4j0mqvoquathjurro3st6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWxV5JK9ISAj3gKe0Nor7antp56jmJw9U',
    appId: '1:819197900013:web:da5452014351782414c8e4',
    messagingSenderId: '819197900013',
    projectId: 'firetest-cdce4',
    authDomain: 'firetest-cdce4.firebaseapp.com',
    storageBucket: 'firetest-cdce4.appspot.com',
  );
}
